[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]

[profile.dependencies]
OpenZeppelin="openzeppelin/openzeppelin-contracts@v5.0.0"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
